### ISSUE TITLE
masquerade works in one direction

### ISSUE THREAD

**Issue by chocosnat** [flannel-io/flannel#1142]
## work without IP masquerading when DirectRouting is set to a false 
There are several pod on the same node. I expect i'll capture traffic with flannel* ip addresses on the virtual network interfaces
I see the CIDR IP address in the client->server flow, and flannel ip address in the server->client flow, tcpdump works on the virtual interface on server side. For example, 10.96.1.15 => 100.68.7.5
I see the flannel ip addresses in the server->client, for example 10.96.1.16 => 10.96.1.15, tcpdump works on the virtual interface on the client side. Client sends RST because IP src hasn't been restored

## work without IP masquerading when DirectRouting is set to the true 
There are several pod on the same node. I expect i'll capture traffic with flannel* ip addresses on the virtual network interfaces 
I see the CIDR IP address in the client->server flow, and flannel ip address in the server->client flow, tcpdump works on the virtual interface on server side. For example, 10.96.1.15 => 100.68.7.5
I see the flannel ip addresses in the server->client, for example 10.96.1.16 => 10.96.1.15, tcpdump works on the virtual interface on the client side. Client sends RST because IP src hasn't been restored

## Steps to Reproduce (for bugs)
1. Use RedHat 7.5 or RedHat 7.6
2. Use vxlan 
3. Set DirectRouting to a false
4. Install one client and one server pod on the same node
5. Fix connectivity problems and capture traffic on the virtual interfaces

## Your Environment
* Flannel 0.11.0 and 0.10.0
* Backend used is vxlan 
* Kubernetes version is 1.12 and 1.13
* redhat 7.5 and 7.6

**Comment by dirtegov-kublr** [comment]
We found that the issue is caused by missing br_netfilter module.
On RHeL 7.6 this module is not loaded by default, so the packets in linux kernel bridge are not processed by netfilter.
So, when we try to access the pod on the same node by service IP, the TCP connection request is DNAT'ed to pod IP, but the response is not NAT'ed back, so connection is not established.

# modprobe br_netfilter 
resolves the issue.

It does not seem to be dependent on DirectRouting flag.

Probably it is a good idea to force modprobe br_netfilter in flannel init sequence.
