### ISSUE TITLE
HTTP readiness/liveness probes always fail from Windows node against container running on same node

### ISSUE THREAD

**Issue by dcopestake** [flannel-io/flannel#1170]
## Expected Behavior
If I configure a readiness/liveness probe for a Windows container in a pod and that container is functioning as expected, I expect the probe to succeed and the pod to continue running.

## Current Behavior
Readiness/liveness probes using `httpGet` always seem to fail causing a never-ending loop of pods being terminated and recreated.

## Steps to Reproduce
1. Add Windows node to a K8s cluster running in overlay mode
2. Create a pod with a Windows container which exposes an HTTP endpoint and a liveness/readiness `httpGet` probe that queries that endpoint
3. Grab the pod IP
4. Query the readiness probe target using the pod IP from a Linux node and confirm it succeeds
5. Query the readiness probe target using the pod IP from the Windows node and note that it times out

## Context
I'm trying to migrate some legacy Windows applications into K8s and wanted to use readiness probes to confirm my pods are up and running. Unfortunately this issue means I have to use the `exec` form of the readiness probe instead.

## Your Environment

* Flannel version: 0.11.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.3.10
* Kubernetes version (if used): 1.15.1
* Operating System and version: Windows Server 2019 1809 (17763)

I've uploaded the [route table](https://github.com/coreos/flannel/files/3540852/route-table.txt) for the Windows node just in case that helps. I assume there should be routes configured for the pod network CIDR but I don't see any?

## Attachments
* [route-table.txt](https://github.com/coreos/flannel/files/3540852/route-table.txt)
* [net-conf.json](https://github.com/coreos/flannel/files/3540864/net-conf.json.txt)
* [cni.conf](https://github.com/coreos/flannel/files/3540865/cni.conf.txt)

**Comment by pintonunes** [comment]
Same here

**Comment by benmoss** [comment]
I think this is because while https://github.com/coreos/flannel/pull/1096 has been merged, it is not part of 0.11.0. You can confirm this by running `Get-HNSNetwork | ? Type -eq Overlay | Select-Object Name, Policies | ConvertTo-Json` and seeing that there's no policy that looks like `"@{Type=HostRoute}"`. 

Give this a shot to see if it fixes your problem: https://github.com/benmoss/fix-houstroute-policy/blob/master/README.md

You can also use the flanneld.exe from https://github.com/benmoss/flannel/releases/download/v0.12.0-rc1/flanneld.exe, which is built from https://github.com/benmoss/flannel/commit/2140ac876ef134e0ed5af15c65e414cf26827915
