### ISSUE TITLE
Flannel down when master lost its internet access (wireless)

### ISSUE THREAD

**Issue by zkf85** [flannel-io/flannel#1414]
## Expected Behavior

We've built a two-node local cluster with flannel via ethernet. The flannel is expected to work no matter if there's internet access (wireless) on any node.

## Current Behavior

However, the flannel stops working when the wireless internet access on master node drops. And it cannot be successfully restarted. The logs are like:

```
Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-tnqqv': ...
```

Specifically, the logs are very similar to that in #1409. But in our case the problem occurs only when the wireless internet drops.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by Oats87** [comment]
Can you check the endpoints of the `kubernetes` service within your cluster and confirm whether the endpoint IP for your `kubernetes` service in the `default` namespace corresponds to the IP that is assigned to your wireless interface?

If this is the case, then having Flannel fail is expected behavior when Flannel is unable to communicate with the K8s API server.
