### ISSUE TITLE
Tests failing on ARM64 platform

### ISSUE THREAD

**Issue by odidev** [flannel-io/flannel#1517]
Hi Team, 
I have been working on running and testing Flannel on arm64 platform but the `make test` command fails on arm64 platform with the following error: 

`etcd cluster is unavailable or misconfigured` 

Since the make test command works fine on amd64 platform I changed etcd version in `functional-test.sh` to latest 3.5.1 which gave the following error: 

`Couldn't fetch network config: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint`  

I followed  recommendations given [here](https://github.com/flannel-io/flannel/issues/1191) but following the recommendations makes the test command stuck in infinite loop. If you would be able to give some pointers on how to resolve the issue on arm64 platform it would be very helpful. 

Are you interested in enabling testing on arm64 platform in GitHub Actions?

**Comment by odidev** [comment]
Hi Team,
A gentle reminder to take a look at above issue and provide some pointers for resolving the issue on arm64 platform.

**Comment by odidev** [comment]
Hi @luthermonson,
Any updates on above issue?

**Comment by AleksandrNull** [comment]
Sorry, was quite busy and forgot to send MR =(
Since whole build process was done with assumption it will be running on x86 platform to compile and test other platform binaries (using statically compiled qemu binary) there is no good way of fixing it without full build system redesign. 
The commit above solves problem with builds on ARM64 (and probably other architectures like arm,ppc64le, s390x, and mips64le) using explicit definition of ARCH env variable for make command (like ARCH=arm64 make test).
There is no good way of building cross-arch binaries on the other than x86 platform because that functionality is limited by using statically compiled qemu which is usually compiled for x86 only but in this case all the permutations of all the ARCHs are required.
@odidev Please confirm it works for you.

**Comment by odidev** [comment]
Hi @AleksandrNull, 

Thanks for your help, the issue is fixed. The tests were passing after some [modifications](https://github.com/odidev/flannel/commit/115db2568e7702c1832d5c915af038d747273762) in test files but now the ipsec and vxlan tests are failing with same error as [here](https://github.com/flannel-io/flannel/issues/953). 

Would you be interested in adding ARM64 tests in GitHub Actions using self-hosted arm64 runners. If interested, Please have a look at  [worksonarm](https://github.com/WorksOnArm), can get access to ARM H/W through this.

**Comment by odidev** [comment]
Hi @luthermonson @AleksandrNull ,
Any updates on the above issue?

**Comment by odidev** [comment]
Thanks for your help, the issue is fixed as the etcd version has been upgraded to 3. The tests were passing after some modifications that can be seen in the PR.

**PR Link:-** https://github.com/flannel-io/flannel/pull/1626

Would you be interested in adding ARM64 tests in GitHub Actions using self-hosted arm64 runners. If interested, Please have a look at  [worksonarm](https://github.com/WorksOnArm), can get access to ARM H/W through this.

**Comment by odidev** [comment]
Hi @luthermonson @AleksandrNull ,
Kindly take a look on above query.

**Comment by odidev** [comment]
Hi @luthermonson @AleksandrNull ,
Kindly take a look on above query.

**Comment by odidev** [comment]
Hi @luthermonson @AleksandrNull , 
Gentle reminder to take a look on above query.
