### ISSUE TITLE
docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1 can not running 

### ISSUE THREAD

**Issue by bencyq** [flannel-io/flannel#2031]
## Expected Behavior
k8s pod  kube-flannel-ds-vjhqf is ready; docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1 is functioning properly

## Current Behavior
k8s pod  kube-flannel-ds-vjhqf is always at state: Init:RunContainerError
pod kube-flannel-ds-vjhqf failed at 
```
Init Containers:
  install-cni-plugin:
    Container ID:  
    Image:         docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
    Args:
      -f
      /flannel
      /opt/cni/bin/flannel
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      **cannot join network of a non running container: 0aae74cae93531c157f438f6f3aed81ca48f5fff388e3a6b6ddabc6d69837884**
      Exit Code:    128
      Started:      Tue, 13 Aug 2024 10:53:59 +0800
      Finished:     Tue, 13 Aug 2024 10:53:59 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /opt/cni/bin from cni-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xpgnc (ro)
```

## Steps to Reproduce (for bugs)
1. $kubectl join ...
2. $kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
3. $kubectl get pods --all-namespaces
```
NAMESPACE      NAME                                 READY   STATUS                   RESTARTS           AGE
kube-flannel   kube-flannel-ds-vjhqf                0/1     Init:RunContainerError   0                  17d
kube-flannel   kube-flannel-ds-x2xhk                1/1     Running                  0                  19d
kube-flannel   kube-flannel-ds-zzhls                1/1     Running                  0                  19d
kube-system    coredns-7db6d8ff4d-m4282             1/1     Running                  0                  27d
kube-system    coredns-7db6d8ff4d-tchbs             1/1     Running                  0                  27d
kube-system    etcd-k8s-master                      1/1     Running                  1 (27d ago)        27d
kube-system    kube-apiserver-k8s-master            1/1     Running                  1 (27d ago)        27d
kube-system    kube-controller-manager-k8s-master   1/1     Running                  1 (27d ago)        27d
kube-system    kube-proxy-nb2jc                     1/1     Running                  0                  20d
kube-system    kube-proxy-xx8vt                     0/1     CrashLoopBackOff         5170 (2m13s ago)   20d
kube-system    kube-proxy-zc9r8                     1/1     Running                  0                  27d
kube-system    kube-scheduler-k8s-master            1/1     Running                  1 (27d ago)        27d
```
4. $kubectl describe pods kube-flannel-ds-vjhqf -n kube-flannel
```
Name:                 kube-flannel-ds-vjhqf
Namespace:            kube-flannel
Priority:             2000001000
Priority Class Name:  system-node-critical
Service Account:      flannel
Node:                 hd-ascend/10.90.1.237
Start Time:           Fri, 26 Jul 2024 10:57:59 +0800
Labels:               app=flannel
                      controller-revision-hash=bb4dc6cbf
                      k8s-app=flannel
                      pod-template-generation=2
                      tier=node
Annotations:          <none>
Status:               Pending
IP:                   10.90.1.237
IPs:
  IP:           10.90.1.237
Controlled By:  DaemonSet/kube-flannel-ds
Init Containers:
  install-cni-plugin:
    Container ID:  
    Image:         docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
    Args:
      -f
      /flannel
      /opt/cni/bin/flannel
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      cannot join network of a non running container: 0aae74cae93531c157f438f6f3aed81ca48f5fff388e3a6b6ddabc6d69837884
      Exit Code:    128
      Started:      Tue, 13 Aug 2024 10:53:59 +0800
      Finished:     Tue, 13 Aug 2024 10:53:59 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /opt/cni/bin from cni-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xpgnc (ro)
  install-cni:
    Container ID:  
    Image:         docker.io/flannel/flannel:v0.25.5
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
    Args:
      -f
      /etc/kube-flannel/cni-conf.json
      /etc/cni/net.d/10-flannel.conflist
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/cni/net.d from cni (rw)
      /etc/kube-flannel/ from flannel-cfg (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xpgnc (ro)
Containers:
  kube-flannel:
    Container ID:  
    Image:         docker.io/flannel/flannel:v0.25.5
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/bin/flanneld
    Args:
      --ip-masq
      --kube-subnet-mgr
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     100m
      memory:  50Mi
    Environment:
      POD_NAME:           kube-flannel-ds-vjhqf (v1:metadata.name)
      POD_NAMESPACE:      kube-flannel (v1:metadata.namespace)
      EVENT_QUEUE_DEPTH:  5000
    Mounts:
      /etc/kube-flannel/ from flannel-cfg (rw)
      /run/flannel from run (rw)
      /run/xtables.lock from xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xpgnc (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   False 
  Initialized                 False 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  run:
    Type:          HostPath (bare host directory volume)
    Path:          /run/flannel
    HostPathType:  
  cni-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  cni:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  flannel-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-flannel-cfg
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  kube-api-access-xpgnc:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 :NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason          Age                        From     Message
  ----     ------          ----                       ----     -------
  Warning  BackOff         41m (x698821 over 17d)     kubelet  Back-off restarting failed container install-cni-plugin in pod kube-flannel-ds-vjhqf_kube-flannel(75d80e9d-5ae7-4287-9184-ace04731cd62)
  Normal   SandboxChanged  6m27s (x1403921 over 17d)  kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          87s (x702562 over 17d)     kubelet  Container image "docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel1" already present on machine
```

## Context
node can never be ready in k8s cluster 
I'm using an arm64 machine as node to join a x86 cluster, does it matter?

## Your Environment

* Flannel version: flannel:v0.25.5
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):v1.30.1
* Operating System and version:centos7
* Link to your project (optional):

**Comment by bencyq** [comment]
> So the only node that it's failing is the one with arm64? I'll check if the container for arm64 was rightly created. Could you check the logs of the failing pod with kubectl?

Thank you for your reply.
Here is the logs.
```
$ kubectl logs kube-flannel-ds-vjhqf -n kube-flannel
Defaulted container "kube-flannel" out of: kube-flannel, install-cni-plugin (init), install-cni (init)
Error from server (BadRequest): container "kube-flannel" in pod "kube-flannel-ds-vjhqf" is waiting to start: PodInitializing

$ kubectl logs kube-proxy-xx8vt -n kube-system
failed to try resolving symlinks in path "/var/log/pods/kube-system_kube-proxy-xx8vt_7758f284-f039-4aeb-bbf5-11da20d35c8f/kube-proxy/6043.log": lstat /var/log/pods/kube-system_kube-proxy-xx8vt_7758f284-f039-4aeb-bbf5-11da20d35c8f/kube-proxy/6043.log: no such file or directory
```

**Comment by rbrtbnfgl** [comment]
Which is the output for
`kubectl logs kube-flannel-ds-vjhqf -n kube-flannel -c install-cni-plugin`

**Comment by zhangguanzhang** [comment]
```
cricrl ps -a 
```

**Comment by x3nb63** [comment]
I reversed my Kubernetes version from `v1.31.0` to `v1.30.3` and the `flannel-cni-plugin:v1.5.1-flannel2` init-container succeeds making `flannel:v0.25.6` startup fine as a consequence

... so I think there is clearly a problem coming from the changes with Kubernetes `v1.31.0`.

**Comment by thomasferrandiz** [comment]
Hi
I tested flannel with k8s 1.31 on both amd64 and arm64 and I had no issue.
My test was on Ubuntu 24.04.

Can you show the kernel version that you're using and the kernel logs?

**Comment by x3nb63** [comment]
the system is

```
$ uname -a
Linux kc04  6.6.43-flatcar #1 SMP PREEMPT_DYNAMIC Mon Aug  5 20:36:27 -00 2024 x86_64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz GenuineIntel GNU/Linux

$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3975.2.0
VERSION_ID=3975.2.0
BUILD_ID=2024-08-05-2103
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3975.2.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3975.2.0:*:*:*:*:*:*:*"
```

to switch the K8s version I toggle the `/etc/extensions/kubernetes.raw` softlink between `/opt/extensions/kubernetes/kubernetes-v1.30.3-x86-64.raw` and `/opt/extensions/kubernetes/kubernetes-v1.31.0-x86-64.raw`

(this is Flatcars way of "blending in" software utilizing systemd-sysext with their [sysext-bakery](https://github.com/flatcar/sysext-bakery) 

For kernel logs I can't do that right now, as I would need to take down a node to get a clean one and they are all busy.

Note that the kernel version and OS version does not change here, I really only toggle the K8s binaries and reboot to have it all start properly after "blending".

**Comment by x3nb63** [comment]
meanwhile there has been a small kernel + OS update, but this problem here is unchanged.

I had a chance to produce fresh dmesg and journalctl logs, please find them attached:

```
$cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3975.2.1
VERSION_ID=3975.2.1
BUILD_ID=2024-09-04-1623
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3975.2.1 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3975.2.1:*:*:*:*:*:*:*"
```

[kernellogs.txt](https://github.com/user-attachments/files/17185707/kernellogs.txt)
[systemlogs.txt](https://github.com/user-attachments/files/17185708/systemlogs.txt)


this far I don't see how to bring my cluster to Kubernetes 1.31.0 given that Flannel does not come up... appreciate any idea how to approach this.

**Comment by thomasferrandiz** [comment]
@x3nb63 I don't notice anything in `kernellogs.txt` but in `systemlogs.txt` I see several messages like this:
```
Sep 30 07:18:37 kc05 kubelet[1593]: W0930 07:18:37.731843    1593 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: "spec.clusterIP" is not a known field selector: only "metadata.name", "metadata.namespace"
Sep 30 07:18:37 kc05 kubelet[1593]: E0930 07:18:37.731914    1593 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: \"spec.clusterIP\" is not a known field selector: only \"metadata.name\", \"metadata.namespace\"" logger="UnhandledError"
```
which then prevents the flannel pod from starting:
```
Sep 30 07:18:42 kc05 kubelet[1593]: E0930 07:18:42.504821    1593 pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni-plugin\" with CreateContainerConfigError: \"services have not yet been read at least once, cannot construct envvars\"" pod="kube-flannel/kube-flannel-ds-v97wm" podUID="05076276-0f40-42f8-9fde-88caea2027b7"
```


That also explains these messages:
```
Sep 30 07:18:42 kc05 containerd[1478]: time="2024-09-30T07:18:42.215949925Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kured-gk6ff,Uid:4068edf6-a44a-460e-aab4-aac9ad87c23c,Namespace:kube-system,Attempt:3,} failed, error" error="failed to setup network for sandbox \"66d2223255051a00a727d3a5a44c21105e89ca2dd56446e764a3903893d66293\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
```
because the flannel pod is the one that should write `/run/flannel/subnet.env` when it starts.

so it looks like the upgrade somehow breaks the cluster configuration. 
Does  the kube-api server look healthy after the upgrade?

Do you have the possibility to install a new cluster from scratch using version `1.31` instead of upgrading an existing cluster?

**Comment by x3nb63** [comment]
thanks for explaining these connections!

kube-apiserver pods are healthy, however I am now spotting all except one control-plane node still use image `registry.k8s.io/kube-apiserver:v1.25.16` while the nodes think they are at v1.30.3 ...  guess that explains why `spec.clusterIP` can not be used.

Certainly not Flannels fault.

**Comment by x3nb63** [comment]
all right, I follow https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/  to get this sorted

essentially per control-plane node
```
$ kubeadm init phase control-plane all
...
$ kubeadm init phase etcd local
...

# wait for Pods to come up... 

# its now truly at v1.30.3 

$ reboot    #  with Flatcar set to start v1.31.1

# this will bring it to v1.31.1  as shown by kubectl get nodes
```

so far Flannel is still not starting but I progressed

_(I'll update this post once I know what to do while not risking all control-plane nodes)_

**Comment by x3nb63** [comment]
@thomasferrandiz 

after previous step its stuck on a different thing as the "spec.ClusterIP unknown" errors are totally gone. As I see it, kubelet is now at 1.31.1 properly and so are all kube-system Pods on said node. Except for kube-proxy, which also relies on Flannel, I suppose.

The flannel Pod now appears to not come up because of `unknown field "status.hostIPs"` as kubelet complains now. I get this is a rather new feature that became stable in 1.30  (in addition to `status.HostIP`). And well, here is one Problem: it should be spelled `status.HostIPs`  [guessing from here](https://github.com/kubernetes/kubernetes/issues/101565) - hope only the log output is wrong?!

Flannel Pod is still stuck in init on `install-cni-plugin`, which does not even attempt to do its thing. Shows as:

```
$ kubectl -n kube-flannel get pods
NAME                    READY   STATUS                            RESTARTS      AGE
...
kube-flannel-ds-pjvpm   0/1     Init:CreateContainerConfigError   0             44h
...
```

What I dont get is why Flannel Pod would want `status.HostIPs` as its yaml does not use it. see
[kube-flannel-ds-pjvpm.yaml.txt](https://github.com/user-attachments/files/17257480/kube-flannel-ds-pjvpm.yaml.txt)  (it uses `fieldRef:` yes, but not that one)

Which makes me think: 

May it be a problem with DualStack?

This is what `status.HostIPs` is for and Dual Stack is disabled on my cluster. Perhaps therefore its not there?

**Comment by x3nb63** [comment]
there is indeed a issue with upgrading 1.30 -> 1.31 !  See https://github.com/kubernetes/kubernetes/issues/127316 where Calico was affected in very similar way

* first had to manually fix `/etc/kubernetes/manifests/kube-*.yaml` to use the proper images for `v1.30.3` ** for all control-plane nodes** (this must have gone wrong at some point in my upgrade path)
* then new (!) Pods appeared with `status.hostIPs` field
* however `"spec.clusterIP" is not a known field selector` still happened on kubelet startup, preventing flannel and other Pods from starting
* **but** `kube-api-server` was up!  (and kube-controller-manager and kube-scheduler as well)
* manually enabling that `ControlPlaneKubeletLocalMode` feature gate (as above issue says) did not solve it for me, but caused more trouble actually since mine is a multi-control-plane-nodes cluster
* so I modified my external load-balancer for `https://my-control-plane:6443` to only serve from the single v1.31.1 node I already upgraded forward, effectively enforcing all requests to the "public" API be answered by v1.31.1
* that way I could upgrade a second control-plane node to v1.31.1, where kubelet started without error and tadaaa **Flannel started!** on this one
* restarting kubelet on the first v1.31.1 node also made Flannel come up then ... as well as all other Pods
* I then re-enabled this one in the backend of my external load-balancer and had a somewhat reliable public control-plane again
* then walked through all remaining control-plane nodes and the worker nodes

**Comment by thomasferrandiz** [comment]
@x3nb63 good news, thanks for letting us know!
