### ISSUE TITLE
Create azure backend

### ISSUE THREAD

**Issue by eyakubovich** [flannel-io/flannel#240]
Microsoft Azure also supports programmable routes so it should be possible to create a backend for it akin to `gce` and `aws-vpc`.

**Comment by danielschonfeld** [comment]
+1 - we use Azure and could make use of this

**Comment by philips** [comment]
@danielschonfeld Any chance you can help ?

**Comment by danielschonfeld** [comment]
@philips how can I help?

**Comment by danielschonfeld** [comment]
I should also note that we've run into problems when setting static routes with static IPs on Azure.  We're trying to address it with Azure Tech Support, but so far it's been like banging a head into a wall.

I am not certain however, if flannel will run into the same problems as I am not sure if its caused only because of the use of static IPs for the VMs or the use of static routes.  If it's the latter that's causing the issues we're seeing, then you can expect flannel running into the same problem.

The problem being that once you're committed to using this set up, if you add, stop, pause, remove VMs and/or change IPs on VMs defined in the static route table, the whole network freezes for the duration of the operation. When I say freezes, I mean ALLLLLL VMs, not just the one you're updating.

**Comment by tomzhang** [comment]
should we consider to include more cloud as backend service .because this is trend that more and more cloud computing providers has been support programable network routing functions.  like some chinese cloud computing provider like ucloud, aliyun.

my suggestion is why we can creating all of this kind of backend service by using a method like Apache libcloud does , just create a SDK hub for every existed cloud vendors and allow users to select what they need to create a specific cloud provider related network solution to eliminate the duplicated works.
